version: '3'
services:
  client_1:
    build:
      context: .
      dockerfile: Dockerfile-client_1
    volumes:
      - "./client_1.py:/client_1.py"
  client_2:
    build:
      context: .
      dockerfile: Dockerfile-client_2
    volumes:
      - "./client_2.py:/client_2.py"
  redis:
    image: redis
    ports:
      - 6379:6379
